server:
  port: ${PORT:8083}
spring:
  application:
    name: taskbolt
    datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver

